Metadata/cover art refactor

diff --git a/zik b/zik
--- a/zik
+++ b/zik
@@ -3,25 +3,27 @@
 SEARCH_PATH="$HOME/Music"
 SEARCH_EXT="wav\|mp3\|flac\|ogg"
 
+# If the image in the audio file is too small
+MIN_WIDTH=480
+
 ZIK_DIR="$HOME/.zik"
 QUEUE="$ZIK_DIR/fifo"
 COVERS="$ZIK_DIR/covers"
 DAEMON_PID_FILE="$ZIK_DIR/daemon_pid"
 FFPLAY_PID_FILE="$ZIK_DIR/ffplay_pid"
 
+
+
 notif() {
     notify-send "Zik" "$1"
 }
 
 # Write file to fifo
+# TODO: add directories
 add() {
     if [ -f "$1" ]; then
-        # It has to running in background because the player
-        # might not have started yet
         echo "$1" > "$QUEUE"
         notif "Added $1"
-    elif [ -d "$1" ]; then
-        notif "This is a directory $1" 
     fi
 }
 
@@ -55,41 +57,45 @@ wgetcover() {
         sed -n 's/.*<release-group id="\([^"]*\)".*/\1/p'
     )
 
-    # Fetch the image from coverartarchive.org,
-    # if wget fails (exit != 0) then no image found
+    # Get image from coverartarchive.org, if wget fails then no image found
     IMAGE_URL="https://coverartarchive.org/release-group/$MBID/front"
-    return $(wget -qO "$3" "$IMAGE_URL") 
+    wget -qO "$3" "$IMAGE_URL"
+    return $?
 }
 
-# Extract metadata, generate and cache album cover art
-gencover() {
-    META=$(ffmpeg -loglevel error -i "$1" -f ffmetadata -)
-    ARTIST=$(echo "$META" | sed -n 's/^ARTIST=\(.*\)$/\1/Ip')
-    ALBUM=$(echo  "$META" | sed -n 's/^ALBUM=\(.*\)$/\1/Ip')
+# Extract cover if it's not too small. $1: input, $2 output
+extractcover() {
+    WIDTH=$(ffprobe -v error -select_streams v:0 -show_entries stream=width -of default=nw=1:nk=1 "$1")
+    [ $WIDTH -lt $MIN_WIDTH ] && return 1
+    ffmpeg -y -i "$1" -vframes 1 -f image2 "$2"
+    return $?
+}
 
-    if [ -n "$ARTIST" ] && [ -n "$ALBUM" ]; then
+# Find cover image $1: artist, $2: album, $3 audio file
+wallpaper() {
+
+    # If artist or album missing from metadata generate a filename
+    if [ -n "$1" ] && [ -n "$2" ]; then
         COVER="$COVERS/$(\
             echo "$ARTIST-$ALBUM.jpg"   |
             tr '[:upper:]' '[:lower:]'  |
             tr -cd '[:alnum:]._-'
         )"
-    else
-        # If artist or album missing from metadata,
-        # save with the audio file name itself
-        BASENAME=$(basename "$1")
+    else # Else save with the audio file name itself
+        BASENAME=$(basename "$3")
         COVER="$COVERS/$BASENAME.jpg"
     fi
 
     # If doesn't exist already, extract from the audio file or get from the web
     if [ -f "$COVER" ] || 
-        ffmpeg -y -i "$1" -vframes 1 -f image2 "$COVER" 2> /dev/null ||
-        wgetcover "$ARTIST" "$ALBUM" "$COVER"
+        extractcover "$3" "$COVER" ||
+        wgetcover "$1" "$2" "$COVER"
     then
-        # notif "Found cover $COVER"
-        echo "$COVER"
+        feh --no-fehbg --bg-max "$COVER"
     else
-        notif "No cover found for $1"
+        notif "No cover found for $3"
     fi
+
 }
 
 
@@ -106,17 +112,25 @@ daemon() {
     # Exit the loop when everything has been read.
     while read -u 3 FILE; do
         [ -f "$FILE" ] || continue
-        notif "Now playing $FILE" 
 
-        # Set cover as wallpaper
-        # FIXME: unhack this make it run in the background
-        ( COVER=$(gencover "$FILE")
-        if [ -n "$COVER" ] && [ -f "$COVER" ]; then
-            feh --no-fehbg --bg-max "$COVER"
-        fi ) &
+        # Get metadata
+        META=$(ffmpeg -v error -i "$FILE" -f ffmetadata -)
+        ARTIST=$(echo "$META" | sed -n 's/^ARTIST=\(.*\)$/\1/Ip')
+        ALBUM=$(echo  "$META" | sed -n 's/^ALBUM=\(.*\)$/\1/Ip')
+        TITLE=$(echo  "$META" | sed -n 's/^TITLE=\(.*\)$/\1/Ip')
+        TRACK=$(echo  "$META" | sed -n 's/^TRACK=\(.*\)$/\1/Ip')
+
+        if [ -n "$TITLE" ]; then
+            notif "Now playing $ARTIST - $TITLE" 
+        else
+            notif "Now playing $FILE"
+        fi
+
+        # Set cover as wallpaper (in the backgroud, wget can take a while)
+        wallpaper "$ARTIST" "$ALBUM" "$FILE" &
 
         # Play it
-        ffplay -nodisp -autoexit "$FILE" 2> /dev/null &
+        ffplay -nodisp -autoexit "$FILE" &
         FFPLAY_PID=$!
         echo $! > "$FFPLAY_PID_FILE"
         wait $!
